classdef sim_scara_motion_controller
    methods
        function Initialise(obj, link_1, link_2, z_min, z_max, settling_time, P_0, I_0, D_0, P_1, I_1, D_1)
            data = [ ...
                typecast(int32(1), 'uint8'), ...
                typecast(single([ ...
                link_1, link_2, z_min, z_max, settling_time, ...
                P_0, I_0, D_0, P_1, I_1, D_1 ...
                ]), 'uint8') ...
                ];

            obj.SendCommand(data)
        end
        function MoveJoint(obj, axis, angle,time)
            data = [...
                typecast(int32(3),    'uint8'), ...
                typecast(int32(axis), 'uint8'), ...
                typecast(single(angle),'uint8'), ...
                typecast(single(time), 'uint8'), ...
                typecast(int32(zeros(1,8)), 'uint8') ...
                ];
            
            obj.SendCommand(data)
        end
        function MoveJoints(obj, angle_0, angle_1, angle_2, angle_3, time)
            data = [ ...
                typecast(int32(4), 'uint8'), ...
                typecast(single([angle_0, angle_1, angle_2, angle_3, time]), 'uint8'), ...
                typecast(int32(zeros(1,6)), 'uint8') ...
                ];
            
            obj.SendCommand(data)
        end

        function MoveCoord(obj, x, y, z_angle, z, time)
            data = [ ...
                typecast(int32(5), 'uint8'), ...
                typecast(single([x, y, z_angle, z, time]), 'uint8'), ...
                typecast(int32(zeros(1,6)), 'uint8') ...
                ];
            
            obj.SendCommand(data)
        end

        function SendCommand(~, command)
            client = tcpclient('127.0.0.1',9000);
            write(client,command,"uint8");
            disp("sending command...")
            reply = read(client,1,"uint8");
            disp("Received success flag:")
            disp(reply)
        end
    end
end
